#!/usr/bin/env bash

GPU_STATS_JSON="/run/hive/gpu-stats.json"
CUR_MINER="/run/hive/cur_miner"
MEMORY_TEMPS="[]"

# T-REX
TREX_API_URL="http://127.0.0.1:4059/summary"

# GMINER
GMINER_API_URL="http://127.0.0.1:42010/stat"

# LOLMINER
LOLMINER_API_URL="http://127.0.0.1:44444/summary"

function init() {
    nvidia_indexes_array=$(cat "${GPU_STATS_JSON}" 2>/dev/null | jq -c '[ .brand | to_entries[] | select(.value == "nvidia") | .key ]')
    gpus_indexes_array=$(cat "${GPU_STATS_JSON}" 2>/dev/null | jq -c '[ .brand | to_entries[] | select(.value != "cpu") | .key ]')
    if [ "${nvidia_indexes_array}" == "" ] || [ "${nvidia_indexes_array}" == "[]" ]; then
        exit 1
    fi
}

function process_stats() {
    local stats="$1"
    local gpus_array="$2"

    if [ "${stats}" == "" ] || [ "${gpus_array}" == "" ]; then
        return 1
    fi

    for x in ${stats}; do
        local k=$(echo ${gpus_array} | jq -c ".[${x%%,*}]")
        local v=${x#*,}
        if [ "${k}" != "null" ] && [ -n "${k}" ]; then
            local temp=$(jq -ceM ".[${k}] = \"${v}\"" <<< "${MEMORY_TEMPS}")

            if [ $? -eq 0 ]; then
                MEMORY_TEMPS=${temp}
            fi
        fi
    done

    return 0
}

function process_gminer_api() {
    local stats=$(curl -s "${GMINER_API_URL}" | jq -c ' .devices| to_entries[] | select(.value.memory_temperature) | [(.value.gpu_id|tostring), (.value.memory_temperature|tostring)] | join(",")' | tr -d '"')

    process_stats "${stats}" "${gpus_indexes_array}"
}

function process_trex_api() {
    local stats=$(curl -s "${TREX_API_URL}" | jq -c ' .gpus| to_entries[] | select(.value.memory_temperature) | [(.value.gpu_id|tostring), (.value.memory_temperature|tostring)] | join(",")' | tr -d '"')

    process_stats "${stats}" "${nvidia_indexes_array}"
}

function process_lolminer_api() {
    local stats=$(curl -s "${LOLMINER_API_URL}" | jq -c ' .Workers | to_entries[] | select(.value.Mem_Temp) | [(.value.Index|tostring), (.value.Mem_Temp|tostring)] | join(",")' | tr -d '"')

    process_stats "${stats}" "${gpus_indexes_array}"
}

function patch_stats() {
    if [ "${MEMORY_TEMPS}" != "" ] && [ "${MEMORY_TEMPS}" != "[]" ] && jq -ceM "." <<< "${MEMORY_TEMPS}"; then
        cat <<< $(jq -ceM ".mtemp = ${MEMORY_TEMPS}" "${GPU_STATS_JSON}") > "${GPU_STATS_JSON}"
    fi
}

function loop() {
    local last_mod_time=$(date +%s)
    inotifywait -m -q -e modify,create "${GPU_STATS_JSON%/*}" |
        while read -r directory events filename; do
            if [ "${filename}" == "${GPU_STATS_JSON##*/}" ] && [ -s "${GPU_STATS_JSON}" ] && [ $((($(date +%s) - ${last_mod_time}))) -gt 2 ]; then
                MEMORY_TEMPS=$(cat "${GPU_STATS_JSON}" 2>/dev/null | jq -cM ' . | if has("mtemp") then .mtemp else (.temp | .[]=0) end')

                # Tricking the agent so it will wait a bit more for us to be done, not really 3 seconds anyway ;)
                touch -d "3 seconds ago" ${GPU_STATS_JSON}

                if [ -s "${CUR_MINER}" ]; then
                    while read miner; do
                        if [ "${miner}" == "gminer" ]; then
                            process_gminer_api
                        fi
                        if [ "${miner}" == "t-rex" ]; then
                            process_trex_api
                        fi
                        if [ "${miner}" == "lolminer" ]; then
                            process_lolminer_api
                        fi
                    done < ${CUR_MINER}

                    patch_stats > /dev/null 2>&1
                fi

                last_mod_time=$(date +%s)
            fi
        done
}

init
loop
