#!/usr/bin/env bash

GPU_STATS_JSON="/run/hive/gpu-stats.json"
RUNNING_FLAG="/run/hive/MINER_RUN"
MEMORY_TEMPS="[]"

# T-REX
TREX_API_URL="http://127.0.0.1:4059/summary"

# GMINER
GMINER_API_URL="http://127.0.0.1:42010/stat"

# LOLMINER
LOLMINER_API_URL="http://127.0.0.1:44444/summary"

function init() {
    nvidia_indexes_array=$(cat "${GPU_STATS_JSON}" 2>/dev/null | jq -c '[ .brand | to_entries[] | select(.value == "nvidia") | .key ]')
    gpus_indexes_array=$(cat "${GPU_STATS_JSON}" 2>/dev/null | jq -c '[ .brand | to_entries[] | select(.value != "cpu") | .key ]')
    if [ "${nvidia_indexes_array}" == "" ] || [ "${nvidia_indexes_array}" == "[]" ]; then
        exit 1
    fi
}

function process_stats() {
    local stats="$1"
    local gpus_array="$2"

    if [ "${stats}" == "" ] || [ "${gpus_array}" == "" ]; then
        return 1
    fi

    for x in ${stats}; do
        local k=$(echo ${gpus_array} | jq -c ".[${x%%,*}]")
        local v=${x#*,}
        if [ "${k}" != "null" ] && [ -n "${k}" ]; then
            local temp=$(jq -ceM ".[${k}] = \"${v}\"" <<< "${MEMORY_TEMPS}")

            if [ $? -eq 0 ]; then
                MEMORY_TEMPS=${temp}
            fi
        fi
    done

    return 0
}

function process_gminer_api() {
    local stats=$(curl -s "${GMINER_API_URL}" | jq -c ' .devices| to_entries[] | select(.value.memory_temperature) | [(.value.gpu_id|tostring), (.value.memory_temperature|tostring)] | join(",")' | tr -d '"')

    process_stats "${stats}" "${gpus_indexes_array}"
}

function process_trex_api() {
    local stats=$(curl -s "${TREX_API_URL}" | jq -c ' .gpus| to_entries[] | select(.value.memory_temperature) | [(.value.gpu_id|tostring), (.value.memory_temperature|tostring)] | join(",")' | tr -d '"')

    process_stats "${stats}" "${nvidia_indexes_array}"
}

function process_lolminer_api() {
    local stats=$(curl -s "${LOLMINER_API_URL}" | jq -c ' .Workers | to_entries[] | select(.value.Mem_Temp) | [(.value.Index|tostring), (.value.Mem_Temp|tostring)] | join(",")' | tr -d '"')

    process_stats "${stats}" "${gpus_indexes_array}"
}

function patch_stats() {
    if [ "${MEMORY_TEMPS}" != "" ] && [ "${MEMORY_TEMPS}" != "[]" ]; then
        ORIG_GPU_STATS=$(cat ${GPU_STATS_JSON})
        if [ "${ORIG_GPU_STATS}" != "" ]; then
            local temp=$(cat "${GPU_STATS_JSON}" | jq -ceM ".mtemp = ${MEMORY_TEMPS}")
            if [ $? -eq 0 ]; then
                echo $temp > ${GPU_STATS_JSON}
            fi
        fi
    fi
}

function loop() {
    while [[ TRUE ]]; do
        if [ -s "${GPU_STATS_JSON}" ]; then
            inotifywait -qq -e modify -t 12 "${GPU_STATS_JSON}"

            MEMORY_TEMPS=$(cat "${GPU_STATS_JSON}" 2>/dev/null | jq -cM ' . | if has("mtemp") then .mtemp else (.temp | .[]=0) end')

            if [ -f "${RUNNING_FLAG}" ]; then
                process_gminer_api
                process_trex_api
                process_lolminer_api

                patch_stats
            fi
        else
            sleep 1
        fi
    done
}

init
loop
